# Generated by Django 3.1.7 on 2021-05-13 22:05

import django.core.validators
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('ano_lancamento', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2021)], verbose_name='Ano de Lançamento')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True, verbose_name='Slug')),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='itens', verbose_name='Imagem de capa')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('qtd_temporadas', models.PositiveSmallIntegerField(verbose_name='Número de temporadas')),
                ('diretor', models.CharField(max_length=100, verbose_name='Diretor')),
                ('elenco', models.TextField(verbose_name='Elenco')),
                ('categoria', models.ManyToManyField(to='itens.CategoriaItem', verbose_name='Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('ano_lancamento', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2021)], verbose_name='Ano de Lançamento')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True, verbose_name='Slug')),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='itens', verbose_name='Imagem de capa')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('volume', models.PositiveSmallIntegerField(verbose_name='Volume')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('editora', models.CharField(max_length=100, verbose_name='Editora')),
                ('categoria', models.ManyToManyField(to='itens.CategoriaItem', verbose_name='Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('ano_lancamento', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2021)], verbose_name='Ano de Lançamento')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True, verbose_name='Slug')),
                ('imagem', stdimage.models.StdImageField(blank=True, null=True, upload_to='itens', verbose_name='Imagem de capa')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('volume', models.PositiveSmallIntegerField(verbose_name='Volume')),
                ('diretor', models.CharField(max_length=100, verbose_name='Diretor')),
                ('elenco', models.TextField(verbose_name='Elenco')),
                ('categoria', models.ManyToManyField(to='itens.CategoriaItem', verbose_name='Categoria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
