# Generated by Django 3.1.7 on 2021-04-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('ano_lancamento', models.DateField(verbose_name='Ano de lançamento')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('volume', models.PositiveSmallIntegerField(verbose_name='Volume')),
                ('diretor', models.CharField(max_length=100, verbose_name='Diretor')),
                ('elenco', models.TextField(verbose_name='Elenco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('ano_lancamento', models.DateField(verbose_name='Ano de lançamento')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('volume', models.PositiveSmallIntegerField(verbose_name='Volume')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('editora', models.CharField(max_length=100, verbose_name='Editora')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, null=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('ano_lancamento', models.DateField(verbose_name='Ano de lançamento')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug')),
                ('qtd_temporadas', models.PositiveSmallIntegerField(verbose_name='Número de temporadas')),
                ('diretor', models.CharField(max_length=100, verbose_name='Diretor')),
                ('elenco', models.TextField(verbose_name='Elenco')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
