# Generated by Django 3.1.7 on 2021-05-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, verbose_name='Slug'),
        ),
    ]
