# Generated by Django 3.1.7 on 2021-04-27 01:30

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='imagem',
            field=stdimage.models.StdImageField(null=True, upload_to='itens', verbose_name='Imagem de capa'),
        ),
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=stdimage.models.StdImageField(null=True, upload_to='itens', verbose_name='Imagem de capa'),
        ),
        migrations.AddField(
            model_name='serie',
            name='imagem',
            field=stdimage.models.StdImageField(null=True, upload_to='itens', verbose_name='Imagem de capa'),
        ),
    ]
