# Generated by Django 3.1.7 on 2021-04-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='filme',
            name='data_atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='filme',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='livro',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='livro',
            name='data_atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='livro',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='serie',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='serie',
            name='data_atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='serie',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de Criação'),
        ),
    ]
