# Generated by Django 3.1.7 on 2021-05-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0003_avaliacao_user_id'),
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, to='avaliacoes.Avaliacao'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, to='avaliacoes.Avaliacao'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, to='avaliacoes.Avaliacao'),
        ),
    ]
