# Generated by Django 3.1.7 on 2021-05-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_auto_20210510_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255, verbose_name='Categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='filme',
            name='avaliacoes',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='avaliacoes',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='avaliacoes',
        ),
        migrations.AddField(
            model_name='filme',
            name='categoria',
            field=models.ManyToManyField(to='itens.CategoriaItem', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ManyToManyField(to='itens.CategoriaItem', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='serie',
            name='categoria',
            field=models.ManyToManyField(to='itens.CategoriaItem', verbose_name='Categoria'),
        ),
    ]
