# Generated by Django 3.1.7 on 2021-05-24 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_auto_20210523_0626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='categoria',
        ),
        migrations.AddField(
            model_name='filme',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.categoriaitem', verbose_name='Categoria'),
        ),
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.categoriaitem', verbose_name='Categoria'),
        ),
        migrations.RemoveField(
            model_name='serie',
            name='categoria',
        ),
        migrations.AddField(
            model_name='serie',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itens.categoriaitem', verbose_name='Categoria'),
        ),
    ]
