# Generated by Django 3.1.7 on 2021-04-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_auto_20210427_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Estagio'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Estagio'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Estagio'),
        ),
    ]
