# Generated by Django 3.1.7 on 2021-05-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_auto_20210528_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='titulo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Título'),
        ),
    ]
