# Generated by Django 3.1.7 on 2021-05-06 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField(max_length='500', verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(choices=[(1, 'Like'), (2, 'Deslike')], verbose_name='Like')),
                ('comentario', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='comentarios.comentario')),
            ],
        ),
    ]
