# Generated by Django 3.1.7 on 2021-05-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioFilme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField(max_length='1024', verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComentarioLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField(max_length='1024', verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComentarioSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField(max_length='1024', verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LikeComentarioFilme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(choices=[(1, 'Like'), (2, 'Deslike')], verbose_name='Like')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LikeComentarioLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(choices=[(1, 'Like'), (2, 'Deslike')], verbose_name='Like')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LikeComentarioSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('like', models.IntegerField(choices=[(1, 'Like'), (2, 'Deslike')], verbose_name='Like')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comentarios.comentarioserie')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
