# Generated by Django 3.1.7 on 2021-05-05 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='comentario',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='comentarios.comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comentarios.comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length='500', verbose_name='Comentario'),
        ),
    ]
