# Generated by Django 3.1.7 on 2021-05-05 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0001_initial'),
        ('comentarios', '0002_auto_20210504_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='publicacao',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='publicacoes.publicacao'),
        ),
    ]
