# Generated by Django 3.1.7 on 2021-05-30 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20210527_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecomentariofilme',
            name='like',
        ),
        migrations.RemoveField(
            model_name='likecomentariolivro',
            name='like',
        ),
        migrations.RemoveField(
            model_name='likecomentarioserie',
            name='like',
        ),
    ]
