# Generated by Django 3.1.7 on 2021-04-28 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(1, 'Péssimo'), (2, 'Ruim'), (3, 'Normal'), (4, 'Legal'), (5, 'Muito bom')], verbose_name='Avaliação')),
                ('msg', models.TextField(verbose_name='Mensagem')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
        ),
    ]
