# Generated by Django 3.1.7 on 2021-05-13 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itens', '0001_initial'),
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoserie',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
        migrations.AddField(
            model_name='avaliacaolivro',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.livro'),
        ),
        migrations.AddField(
            model_name='avaliacaolivro',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
        migrations.AddField(
            model_name='avaliacaofilme',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.filme'),
        ),
        migrations.AddField(
            model_name='avaliacaofilme',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
    ]
