# Generated by Django 3.1.7 on 2021-05-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_auto_20210527_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofilme',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='avaliacaolivro',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='avaliacaoserie',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Criação'),
        ),
    ]
