# Generated by Django 3.1.7 on 2021-05-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_auto_20210513_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaofilme',
            name='avaliacao',
            field=models.CharField(max_length=200, null=True, verbose_name='Comentário'),
        ),
        migrations.AddField(
            model_name='avaliacaolivro',
            name='avaliacao',
            field=models.CharField(max_length=200, null=True, verbose_name='Comentário'),
        ),
        migrations.AddField(
            model_name='avaliacaoserie',
            name='avaliacao',
            field=models.CharField(max_length=200, null=True, verbose_name='Comentário'),
        ),
    ]
