# Generated by Django 3.1.7 on 2021-05-05 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_auto_20210504_2238'),
        ('avaliacoes', '0002_auto_20210430_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comentarios.comentario'),
        ),
    ]
