# Generated by Django 3.1.7 on 2021-05-11 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itens', '0003_auto_20210510_2247'),
        ('avaliacoes', '0003_avaliacao_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoFilme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Avaliação')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.filme')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Avaliação')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.livro')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Avaliação')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itens.serie')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user_id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
