# Generated by Django 3.1.7 on 2021-05-13 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210513_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cidade', verbose_name='Cidade'),
        ),
    ]
