# Generated by Django 3.1.7 on 2021-04-19 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210415_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla')),
            ],
        ),
        migrations.DeleteModel(
            name='Cidades',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(choices=[], max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estado', verbose_name='Estado'),
        ),
    ]
