# Generated by Django 3.1.7 on 2021-05-20 23:08

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pedidosamizade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='usuarios', verbose_name='Imagem Perfil'),
        ),
    ]
